# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yuchen Wu
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/bay" # the subpath of the site
url: "https://eliottvincent.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile.jpeg
google_analytics: "UA-121636368-3"

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: wuyc14@stanford.edu
      link: mailto:wuyc14@stanford.edu
   # - name: WeChat
   #   value: YourWeChatUsername
   #   link: "#"
  follow:
    - name: Twitter
      link: https://twitter.com/YuchenW50977030
      #username: "@YourTwitterUsername"
    - name: Facebook
      link: https://www.facebook.com/wu.yuchen.750
    - name: LinkedIn
      link: https://www.linkedin.com/in/yuchen-wu-aab9b71aa/
    - name: GitHub
      link: https://github.com/wuyc0114
   # - name: Dribbble
   #   link: https://dribbble.com/YourDribbbleUsername
   # - name: Weibo
   #   link: http://weibo.com/u/YourWeiboUsername
   # - name: RSS
   #   link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
