menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Contact', url: '/contact'}


courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/wuyc0114'}
- {icon: 'twitter', link: 'https://twitter.com/YuchenW50977030'}
- {icon: 'Facebook', link: 'https://www.facebook.com/wu.yuchen.750'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yuchen-wu-aab9b71aa/'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
